services:
  - type: web
    name: synthetic-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 main:app"
    envVars:
      - key: JWT_SECRET_KEY
        value: "123"
    pythonVersion: 3.11
